server:
  port: 8080
user-service:
  location: http://localhost:8000/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/products?autoreconnect = true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver